---
title: "Page Visits Funnel"
output: html_notebook
---

```{r message = FALSE, error=TRUE}
# load packages
library(readr)
library(dplyr)
```

```{r message = FALSE, error=TRUE}
# load data
visits <- read_csv("visits.csv")
cart <- read_csv("cart.csv")
checkout <- read_csv("checkout.csv")
purchase <- read_csv("purchase.csv")
```

```{r error=TRUE}
# inspect data frames
head(visits)
head(cart)
head(checkout)
head(purchase)
```

```{r error=TRUE}
# define visits_cart here:
visits_cart <- visits %>%
  left_join(cart)
visits_cart
#
```

```{r error=TRUE}
# define total_visits here:
# Length - 2000 rows. 

```

```{r error=TRUE}
# define visit_no_cart here:
visit_no_cart <- visits_cart %>%
  filter(is.na(cart_time))
visit_no_cart
# na_cart > 1,652 rows meaning that 1652/2000 did not make it to the cart.

```

```{r error=TRUE}
# calculate visit_no_cart_percent here:
# 82.6% of users who visited Cool T-Shirts Inc. did not place a t-shirt in their cart.
```

```{r error=TRUE}
# define cart_checkout here:
#  What percentage of users put items in their cart, but did not proceed to checkout?
cart_checkout <- cart %>%
  left_join(checkout)
cart_checkout
# Length 348 rows
```

```{r error=TRUE}
# define na_checkout here:
na_checkout <- cart_checkout %>%
  filter(is.na(checkout_time))
na_checkout
# Length 122 rows 
```

```{r error=TRUE}
# calculate cart_no_checkout_percent here:
#  122/348 (35.1%) added an item to the cart but did not proceed to the checkout. 
```

```{r error=TRUE}
# define all_data here:
all_data <- visits %>%
  left_join(cart) %>%
  left_join(checkout) %>%
  left_join(purchase)
all_data
```

```{r error=TRUE}
# define total_checkout here:
all_data %>%
  summarise(
    total_checkout = sum(!is.na(checkout_time)),
    no_purchase = sum(!is.na(checkout_time) & is.na(purchase_time)),
    percentage = no_purchase / total_checkout * 100
  )
# total_checkout  no_purchase percentage
# 226	            82	        36.28319
```

```{r error=TRUE}
# define checkout_no_purchase here:
checkout_no_purchase <- all_data %>%
  filter(!is.na(checkout_time) & is.na(purchase_time))
# I.e. is not empty for checkout_time, but IS empty for purchase_time
checkout_no_purchase
```

```{r error=TRUE}
# calculate checkout_no_purchase_percent here:
checkout_no_purchase_percent <- nrow(checkout_no_purchase) / 
  sum(!is.na(all_data$checkout_time)) * 100

checkout_no_purchase_percent
# [1] 36.28319
```

```{r error=TRUE}
# update all_data with time_to_purchase column here:
all_data <- all_data %>%
  mutate(time_to_purchase = purchase_time - visit_time)
```

```{r error=TRUE}
# inspect the updated all_data data frame here:
head(all_data)
```

```{r error=TRUE}
# define time_to_purchase here:
time_to_purchase <- all_data %>%
  summarize(mean_time = mean(time_to_purchase, na.rm = TRUE))
time_to_purchase


```